spring:
  profiles:
    group:
      "memory": "memory, common"
      "development": "development,common"
      "production": "production,common"
    active: memory

springdoc:
  show-actuator: true
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  api-docs:
    path: /api-docs
    api-docs-enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: true
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match:
    - /**

---
spring:
  config:
    activate:
      on-profile: "common"

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.security: debug

---
#h2 Memory
spring:
  config:
    activate:
      on-profile: "memory"
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ryan
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  properties:
    hibernate:
      format_sql: true
      show-sql: true

jwt:
  header: Authorization
  secretKey: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  token-expiration-time: 86400