spring:
  profiles:
    group:
      "memory": "memory, common"
      "local": "local, common"
      "development": "development,common"
      "production": "production,common"
    active: local

---
spring:
  config:
    activate:
      on-profile: "common"
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

server:
  servlet:
    context-path: "/api"
  port: 5001

jwt:
  header: Authorization
  secretKey: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  token-validity-in-seconds: 86400

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.security: debug

---
#h2 Memory
spring:
  config:
    activate:
      on-profile: "memory"
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ryan
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: always
  sql:
    init:
      mode: always
      data-locations: classpath:./db/h2/data.sql
  properties:
    hibernate:
      format_sql: true
      show-sql: true

---
#Local MySql
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/room_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      defer-datasource-initialization: always
  sql:
    init:
      platform: mysql
      mode: always
      data-locations: classpath:./db/mysql/data.sql

  cors-ip:
    url: http://localhost:3000/
